### ISSUE TITLE
Anti-Freeze bug

### ISSUE THREAD

**Issue by Walter-Correa** [CabooseSayzWTF/Demonic-Revelations-RIP-Edition#1]
When activating Anti-Freeze all players are invisible to me, but they can see me. I can only see their icon on the radar with a little arrow up, as if they were above me.

**Comment by xTheDevilRazedMe** [comment]
That's supposed to happen, it unloads every thing that's server side so there isn't anything that can freeze you

**Comment by Walter-Correa** [comment]
> That's supposed to happen, it unloads every thing that's server side so there isn't anything that can freeze you

**First of all I want to say that this menu mod is amazing, congratulations!**
I understood! Isn't there a way to make this script work without making the players invisible?
Because the idea is for you to play normally without being frozen, but playing without seeing anyone is bad! ahahaha

**Comment by CabooseSayzWTF** [comment]
This menu is no longer in support. It is open source, do with it and fix what you like. It is no longer being worked on or updated.
What Devil said is accurate. Considering my skills in reversing is limited, the only proper protections will be plugins as in xex and sprx. Beyond my skill and lack of interest to research it. You are on your own on that front. I have 0 interest in the online side of things anymore. Rockstar can patch there game and deal with the issue there selves. I've warned them time and time again, they didn't listen to me. So maybe one day they will patch all this out, but till then, you will have to handle your own. Sorry.
